// Generates compact, offline geography assets for COGNIS:
//   1. src/components/globe/landDots.ts  – equal-area dot sampling of world land (for the WebGL globe)
//   2. src/components/maps/norwayOutline.ts – projected SVG path of mainland Norway (for location maps)
// Run with: npm run gen:geo   (requires dev deps world-atlas, topojson-client, d3-geo)
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { feature } from 'topojson-client';
import { geoContains, geoBounds } from 'd3-geo';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const atlas = (name) => JSON.parse(readFileSync(resolve(root, 'node_modules/world-atlas', name), 'utf8'));

// ---------- 1. Land dots ----------
const land = feature(atlas('land-110m.json'), atlas('land-110m.json').objects.land);
const STEP = 1.1; // degrees
const pts = [];
for (let lat = -58; lat <= 82; lat += STEP) {
  const lonStep = STEP / Math.max(0.18, Math.cos((lat * Math.PI) / 180));
  for (let lon = -180; lon < 180; lon += lonStep) {
    if (geoContains(land, [lon, lat])) pts.push(Math.round(lat * 100), Math.round(lon * 100));
  }
}
const buf = Buffer.from(new Int16Array(pts).buffer);
const landOut = `// AUTO-GENERATED by scripts/generate-geo.mjs from Natural Earth (world-atlas, public domain).
// ${pts.length / 2} land sample points, encoded as base64 Int16 pairs [lat*100, lon*100].
export const LAND_DOTS_B64 =
  '${buf.toString('base64')}';

export function decodeLandDots(): Float32Array {
  const bin = atob(LAND_DOTS_B64);
  const bytes = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) bytes[i] = bin.charCodeAt(i);
  const ints = new Int16Array(bytes.buffer);
  const out = new Float32Array(ints.length);
  for (let i = 0; i < ints.length; i++) out[i] = ints[i] / 100;
  return out;
}
`;
mkdirSync(resolve(root, 'src/components/globe'), { recursive: true });
writeFileSync(resolve(root, 'src/components/globe/landDots.ts'), landOut);
console.log('land dots:', pts.length / 2);

// ---------- 2. Norway outline ----------
const countries = atlas('countries-50m.json');
const norway = feature(countries, countries.objects.countries).features.find((f) => f.id === '578');
// Simple equirectangular projection with cos(lat0) scaling – easy to reproduce at runtime.
const LAT0 = 65;
const LON_MIN = 4.4;
const LAT_MAX = 71.3;
const K = 40; // px per degree latitude
const COS = Math.cos((LAT0 * Math.PI) / 180);
const proj = ([lon, lat]) => [(lon - LON_MIN) * COS * K, (LAT_MAX - lat) * K];
const polys = norway.geometry.type === 'MultiPolygon' ? norway.geometry.coordinates : [norway.geometry.coordinates];
let d = '';
let maxX = 0;
let maxY = 0;
for (const poly of polys) {
  const [[minLon, minLat], [maxLon, maxLat]] = geoBounds({ type: 'Polygon', coordinates: poly });
  // mainland + coastal islands only (skip Svalbard / Jan Mayen)
  if (maxLat > 71.5 || minLon < 3 || (maxLon - minLon) * (maxLat - minLat) < 0.004) continue;
  const ring = poly[0];
  ring.forEach((p, i) => {
    const [x, y] = proj(p);
    maxX = Math.max(maxX, x);
    maxY = Math.max(maxY, y);
    d += `${i === 0 ? 'M' : 'L'}${x.toFixed(1)} ${y.toFixed(1)}`;
  });
  d += 'Z';
}
const nOut = `// AUTO-GENERATED by scripts/generate-geo.mjs from Natural Earth (world-atlas, public domain).
// Mainland Norway outline, equirectangular projection scaled by cos(${LAT0}°).
export const NORWAY_PATH = '${d}';
export const NORWAY_VIEWBOX = { width: ${Math.ceil(maxX)}, height: ${Math.ceil(maxY)} };

/** Project a WGS84 coordinate into the NORWAY_PATH coordinate space. */
export function projectNorway(lat: number, lon: number): [number, number] {
  return [(lon - ${LON_MIN}) * ${COS.toFixed(6)} * ${K}, (${LAT_MAX} - lat) * ${K}];
}
`;
mkdirSync(resolve(root, 'src/components/maps'), { recursive: true });
writeFileSync(resolve(root, 'src/components/maps/norwayOutline.ts'), nOut);
console.log('norway path chars:', d.length, 'viewbox', Math.ceil(maxX), Math.ceil(maxY));
